//#define DEBUG

#include <iostream>
#include <bitset>
#include <fstream>
#include "Exceptions.h"
#include "BSHelper.h"
#include "DES.h"

std::string GetSelection(std::string menu, std::vector<std::string> options)
{
  bool validOption = false;
  std::string selection;
  while (!validOption)
  {
    std::cout << "\n" << menu;
    std::cout << "\nYour selection: ";
    std::cin >> selection;
    std::cout << "\n\n";

    for(int i = 0; i < options.size(); i++)
      if(selection == options[i])
        validOption = true;
    if(!validOption)
      std::cout << "Invalid option selected.\n";
  }
  return selection;
}

std::string GetData(bool hexOnly)
{
  bool validFile = false;
  std::string path;
  std::string output;
  while (!validFile)
  {
    std::cout << "\nInput file name: ";
    std::cin >> path;
//    for(int i = 0; i < path.length(); i++)
//      if(path[i] == '.')
//      {
//        path = path.substr(0, i);
//        break;
//      }

    try
    {
      std::ifstream file;
      file.open(path.c_str());
      if (file.is_open())
      {
        while (!file.eof())
          file >> output;
        file.close();
        validFile = (output.length() > 0);
      }
      else
      {
        std::cout << "\n\nCould not read from file.\n";
        std::cout << "Only enter the filename (with the extension), such as \"/home/username/Desktop/file.txt\".\n";
        std::cout << "If the file was generated by this program, you can enter the name without the path (like \"EncryptedData.txt\")";
      }
    }
    catch(const std::exception& e)
    {
      std::cout << "\n\nCould not read from file.\n";
      std::cout << "Only enter the filename (with the extension), such as \"/home/username/Desktop/file.txt\".\n";
      std::cout << "If the file was generated by this program, you can enter the name without the path (like \"EncryptedData.txt\")";
    }
  }

  std::string selection;
  if(!hexOnly)
  {
    std::vector<std::string> options;
    options.push_back("1");
    options.push_back("2");
    selection = GetSelection("What is the file encoding?\n1- ASCII\n2- Hexadecimal", options);
  }
  else
    selection = "2";

  if(selection == "1")
    return BSHelper::AsciiToBits(output);
  return BSHelper::HexToBits(output);
}

std::string GetKey()
{
  bool validKey = false;
  std::string key;
  while (!validKey)
  {
    std::cout << "\nInput 16-digit hex key: ";
    std::cin >> key;

    if(key.length() != 16)
      std::cout << "\nInvalid key length. Must be 16 hex digits.";
    else
    {
      try
      {
        key = BSHelper::HexToBits(key);
        #ifdef DEBUG
        std::cout << "\n\nKey Binary: \n" << key << '\n';
        #endif // DEBUG
        return key;
      }
      catch(ConversionException e)
      {
        std::cout << "\nInvalid key input / length. Must be 16 hex digits.";
      }
    }
  }
}

bool WriteToFile(std::string path, std::string data)
{
  try
  {
    std::ofstream file;
    file.open (path.c_str());
    file << data;
    file.close();
    return true;
  }
  catch(ConversionException e)
  {
    return false;
  }
}

int main(int argc, char** argv)
{
  DES des;

  std::cout << " _____  _______ ______\n|     \\|    ___|    __|\n|  --  |    ___|__    |\n|_____/|_______|______|\nENCRYPTION & DECRYPTION\n\n";
  std::cout << "CPSC 3730  CRYPTOGRAPHY\n";
  std::cout << "PROGRAMMING  ASSIGNMENT\n";
  std::cout << "   BY KYLE AKERSTROM\n\n";

  bool running = true;
  while(running)
  {
    std::vector<std::string> yesno;
    yesno.push_back("1");
    yesno.push_back("2");
    std::vector<std::string> options;
    options.push_back("1");
    options.push_back("2");
    //options.push_back("3");
    std::string input = GetSelection("1- Encrypt\n2- Decrypt", options);

    if(input == "1")
    {
      std::string data = GetData(false);
      std::string key = GetKey();
      std::string output = des.Encrypt(data, key);
      for(int n = 0; n < 100; n++)
        std::cout << '\n';
      std::cout << "\n\n\n\n\n\n\n\n\n\nEncrypted cipher-text: ";
      output = BSHelper::BitsToHex(output);
      std::cout << output;
      if(WriteToFile("EncryptedData.txt", output))
        std::cout << "\n\nData has been written to EncryptedData.txt.\n\n";
      std::string selection = GetSelection("Would you like to encrypt or decrypt another file?\n\n1- Yes\n2- No", yesno);
      if(selection == "2")
        running = false;
    }
    else if (input == "2")
    {
      std::string data = GetData(true);
      std::string key = GetKey();
      std::string output = des.Decrypt(data, key);
      for(int n = 0; n < 100; n++)
        std::cout << '\n';
      std::cout << "\n\n\n\n\n\n\n\n\n\nDecrypted plain-text: ";
      output = BSHelper::BitsToAscii(output);
      std::cout << output;
      if(WriteToFile("DecryptedData.txt", output))
        std::cout << "\n\nData has been written to DecryptedData.txt.\n\n";
      std::string selection = GetSelection("Would you like to encrypt or decrypt another file?\n\n1- Yes\n2- No", yesno);
      if(selection == "2")
        running = false;
    }
    for(int n = 0; n < 100; n++)
      std::cout << '\n';
//    else if (input == "3")
//    {
//      std::cout << "\nInput ASCII data (with no spaces): ";
//      std::string data;
//      std::cin >> data;
//      std::string key = GetKey();
//      std::string output = des.Encrypt(data, key);
//      std::cout << "\n\nENCRYPTED: " << BSHelper::BitsToHex(output) << '\n';
//      output = des.Decrypt(output, key);
//      std::cout << "DECRYPTED:   " << BSHelper::BitsToAscii(output) << "\n\n";
//      std::string selection = GetSelection("Would you like to encrypt or decrypt another file?\n\n1- Yes\n2- No", yesno);
//      if(selection == "2")
//        running = false;
//    }
  }

}
